name: Check for updates
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}
jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ master ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork com.usebottles.bottles.yml
